-- =========================================================
-- Coupons: USDT denomination + bulk creation with autogenerated codes
-- - Adds `currency` ('seed' | 'usdt') to coupons (default 'seed').
-- - redeem_coupon converts USDT coupons to Seed at the current rate.
-- - admin_create_coupon gains a currency argument.
-- - admin_create_coupons_bulk generates N coupons with unique random codes.
-- All admin RPCs are SECURITY DEFINER, gated by is_admin(auth.uid()), and audited.
-- =========================================================

-- 1. Currency column --------------------------------------------------------
ALTER TABLE public.coupons
  ADD COLUMN IF NOT EXISTS currency text NOT NULL DEFAULT 'seed'
  CHECK (currency IN ('seed', 'usdt'));

-- 2. redeem_coupon — convert USDT coupons to Seed at the current rate -------
CREATE OR REPLACE FUNCTION public.redeem_coupon(p_code text)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_user   uuid := auth.uid();
  v_coupon public.coupons%ROWTYPE;
  v_wallet public.wallets%ROWTYPE;
  v_red_id uuid;
  v_rate   numeric;
  v_credit numeric(20,8);
BEGIN
  IF v_user IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  IF p_code IS NULL OR length(trim(p_code)) = 0 THEN RAISE EXCEPTION 'Code required'; END IF;

  SELECT * INTO v_coupon FROM public.coupons WHERE code = upper(trim(p_code)) FOR UPDATE;
  IF v_coupon.id IS NULL THEN RAISE EXCEPTION 'Invalid coupon code'; END IF;
  IF NOT v_coupon.active THEN RAISE EXCEPTION 'Coupon is inactive'; END IF;
  IF v_coupon.expires_at IS NOT NULL AND v_coupon.expires_at < now() THEN
    RAISE EXCEPTION 'Coupon has expired';
  END IF;
  IF v_coupon.used_redemptions >= v_coupon.max_redemptions THEN
    RAISE EXCEPTION 'Coupon fully redeemed';
  END IF;
  IF EXISTS (SELECT 1 FROM public.coupon_redemptions WHERE coupon_id = v_coupon.id AND user_id = v_user) THEN
    RAISE EXCEPTION 'Already redeemed';
  END IF;

  SELECT * INTO v_wallet FROM public.wallets WHERE user_id = v_user AND kind = 'primary';
  IF v_wallet.id IS NULL THEN RAISE EXCEPTION 'Primary wallet not found'; END IF;

  -- Wallets hold Seed. A USDT coupon is converted using app_settings.seed_to_usdt
  -- (the USDT value of 1 Seed), so Seed credited = usdt_amount / rate.
  IF v_coupon.currency = 'usdt' THEN
    SELECT seed_to_usdt INTO v_rate FROM public.app_settings WHERE id = true;
    IF v_rate IS NULL OR v_rate <= 0 THEN RAISE EXCEPTION 'Conversion rate unavailable'; END IF;
    v_credit := round(v_coupon.amount / v_rate, 8);
  ELSE
    v_credit := v_coupon.amount;
  END IF;
  IF v_credit <= 0 THEN RAISE EXCEPTION 'Nothing to credit'; END IF;

  INSERT INTO public.coupon_redemptions (coupon_id, user_id, amount)
  VALUES (v_coupon.id, v_user, v_credit)
  RETURNING id INTO v_red_id;

  UPDATE public.coupons SET used_redemptions = used_redemptions + 1 WHERE id = v_coupon.id;

  PERFORM public.wallet_adjust(
    v_wallet.id, v_credit,
    'coupon_redeem'::ledger_kind,
    'Coupon ' || v_coupon.code, 'coupons', v_coupon.id
  );

  RETURN v_red_id;
END $$;

-- 3. admin_create_coupon — now accepts a currency --------------------------
DROP FUNCTION IF EXISTS public.admin_create_coupon(text, numeric, integer, timestamptz);

CREATE OR REPLACE FUNCTION public.admin_create_coupon(
  p_code     text,
  p_amount   numeric,
  p_max      integer,
  p_currency text DEFAULT 'seed',
  p_expires  timestamptz DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_admin uuid := auth.uid();
  v_id    uuid;
  v_code  text := upper(trim(p_code));
  v_cur   text := lower(coalesce(p_currency, 'seed'));
BEGIN
  IF v_admin IS NULL OR NOT public.is_admin(v_admin) THEN RAISE EXCEPTION 'Admin only'; END IF;
  IF v_code IS NULL OR length(v_code) = 0 THEN RAISE EXCEPTION 'Code required'; END IF;
  IF p_amount IS NULL OR p_amount <= 0 THEN RAISE EXCEPTION 'Amount must be positive'; END IF;
  IF p_max IS NULL OR p_max < 1 THEN RAISE EXCEPTION 'Max redemptions must be >= 1'; END IF;
  IF v_cur NOT IN ('seed', 'usdt') THEN RAISE EXCEPTION 'Invalid currency'; END IF;

  INSERT INTO public.coupons (code, amount, max_redemptions, expires_at, active, created_by, currency)
  VALUES (v_code, p_amount, p_max, p_expires, true, v_admin, v_cur)
  RETURNING id INTO v_id;

  PERFORM public.admin_audit(v_admin, 'coupon_created', 'coupon', v_id,
    jsonb_build_object('code', v_code, 'amount', p_amount, 'max', p_max, 'currency', v_cur));
  RETURN v_id;
END $$;

-- 4. admin_create_coupons_bulk — N coupons with unique random codes --------
CREATE OR REPLACE FUNCTION public.admin_create_coupons_bulk(
  p_count    integer,
  p_amount   numeric,
  p_max      integer,
  p_currency text DEFAULT 'seed',
  p_expires  timestamptz DEFAULT NULL,
  p_prefix   text DEFAULT NULL
)
RETURNS text[]
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  v_admin    uuid := auth.uid();
  v_cur      text := lower(coalesce(p_currency, 'seed'));
  v_prefix   text := upper(regexp_replace(coalesce(p_prefix, ''), '[^A-Za-z0-9]', '', 'g'));
  v_codes    text[] := ARRAY[]::text[];
  v_code     text;
  i          integer;
BEGIN
  IF v_admin IS NULL OR NOT public.is_admin(v_admin) THEN RAISE EXCEPTION 'Admin only'; END IF;
  IF p_count IS NULL OR p_count < 1 OR p_count > 500 THEN RAISE EXCEPTION 'Count must be between 1 and 500'; END IF;
  IF p_amount IS NULL OR p_amount <= 0 THEN RAISE EXCEPTION 'Amount must be positive'; END IF;
  IF p_max IS NULL OR p_max < 1 THEN RAISE EXCEPTION 'Max redemptions must be >= 1'; END IF;
  IF v_cur NOT IN ('seed', 'usdt') THEN RAISE EXCEPTION 'Invalid currency'; END IF;
  IF length(v_prefix) > 12 THEN RAISE EXCEPTION 'Prefix too long'; END IF;

  FOR i IN 1..p_count LOOP
    -- Retry until a unique random code lands.
    LOOP
      v_code := v_prefix || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 8));
      BEGIN
        INSERT INTO public.coupons (code, amount, max_redemptions, expires_at, active, created_by, currency)
        VALUES (v_code, p_amount, p_max, p_expires, true, v_admin, v_cur);
        v_codes := array_append(v_codes, v_code);
        EXIT;
      EXCEPTION WHEN unique_violation THEN
        -- collision: loop and try a new code
      END;
    END LOOP;
  END LOOP;

  PERFORM public.admin_audit(v_admin, 'coupons_bulk_created', 'coupon', NULL,
    jsonb_build_object('count', p_count, 'amount', p_amount, 'max', p_max,
                       'currency', v_cur, 'prefix', v_prefix));
  RETURN v_codes;
END $$;

-- 5. Grants -----------------------------------------------------------------
GRANT EXECUTE ON FUNCTION public.admin_create_coupon(text, numeric, integer, text, timestamptz) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.admin_create_coupons_bulk(integer, numeric, integer, text, timestamptz, text) TO authenticated, service_role;
